// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NativePubSub.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PJ.Native.Proto {

  /// <summary>Holder for reflection information generated from NativePubSub.proto</summary>
  public static partial class NativePubSubReflection {

    #region Descriptor
    /// <summary>File descriptor for NativePubSub.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NativePubSubReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJOYXRpdmVQdWJTdWIucHJvdG8iUgoHTWVzc2FnZRILCgNrZXkYASABKAkS",
            "HQoJY29udGFpbmVyGAIgASgLMgouQ29udGFpbmVyEhsKCGVudmVsb3BlGAMg",
            "ASgLMgkuRW52ZWxvcGUiuQQKCUNvbnRhaW5lchIqCghib29sZWFucxgBIAMo",
            "CzIYLkNvbnRhaW5lci5Cb29sZWFuc0VudHJ5EioKCGludGVnZXJzGAIgAygL",
            "MhguQ29udGFpbmVyLkludGVnZXJzRW50cnkSJgoGZmxvYXRzGAMgAygLMhYu",
            "Q29udGFpbmVyLkZsb2F0c0VudHJ5EigKB3N0cmluZ3MYBCADKAsyFy5Db250",
            "YWluZXIuU3RyaW5nc0VudHJ5EiQKBWJ5dGVzGAUgAygLMhUuQ29udGFpbmVy",
            "LkJ5dGVzRW50cnkSLgoKY29udGFpbmVycxgGIAMoCzIaLkNvbnRhaW5lci5D",
            "b250YWluZXJzRW50cnkaLwoNQm9vbGVhbnNFbnRyeRILCgNrZXkYASABKAkS",
            "DQoFdmFsdWUYAiABKAg6AjgBGi8KDUludGVnZXJzRW50cnkSCwoDa2V5GAEg",
            "ASgJEg0KBXZhbHVlGAIgASgFOgI4ARotCgtGbG9hdHNFbnRyeRILCgNrZXkY",
            "ASABKAkSDQoFdmFsdWUYAiABKAI6AjgBGi4KDFN0cmluZ3NFbnRyeRILCgNr",
            "ZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGiwKCkJ5dGVzRW50cnkSCwoD",
            "a2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ARo9Cg9Db250YWluZXJzRW50",
            "cnkSCwoDa2V5GAEgASgJEhkKBXZhbHVlGAIgASgLMgouQ29udGFpbmVyOgI4",
            "ASJECghFbnZlbG9wZRIQCghzZW5kZXJJRBgBIAEoBRIXCgpyZWNlaXZlcklE",
            "GAIgASgFSACIAQFCDQoLX3JlY2VpdmVySURCJwoTY29tLnBqLnB1YnN1Yi5w",
            "cm90b6oCD1BKLk5hdGl2ZS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PJ.Native.Proto.Message), global::PJ.Native.Proto.Message.Parser, new[]{ "Key", "Container", "Envelope" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PJ.Native.Proto.Container), global::PJ.Native.Proto.Container.Parser, new[]{ "Booleans", "Integers", "Floats", "Strings", "Bytes", "Containers" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::PJ.Native.Proto.Envelope), global::PJ.Native.Proto.Envelope.Parser, new[]{ "SenderID", "ReceiverID" }, new[]{ "ReceiverID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PJ.Native.Proto.NativePubSubReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      key_ = other.key_;
      container_ = other.container_ != null ? other.container_.Clone() : null;
      envelope_ = other.envelope_ != null ? other.envelope_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "container" field.</summary>
    public const int ContainerFieldNumber = 2;
    private global::PJ.Native.Proto.Container container_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PJ.Native.Proto.Container Container {
      get { return container_; }
      set {
        container_ = value;
      }
    }

    /// <summary>Field number for the "envelope" field.</summary>
    public const int EnvelopeFieldNumber = 3;
    private global::PJ.Native.Proto.Envelope envelope_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PJ.Native.Proto.Envelope Envelope {
      get { return envelope_; }
      set {
        envelope_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (!object.Equals(Container, other.Container)) return false;
      if (!object.Equals(Envelope, other.Envelope)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (container_ != null) hash ^= Container.GetHashCode();
      if (envelope_ != null) hash ^= Envelope.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (container_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Container);
      }
      if (envelope_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Envelope);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (container_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Container);
      }
      if (envelope_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Envelope);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (container_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Container);
      }
      if (envelope_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Envelope);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.container_ != null) {
        if (container_ == null) {
          Container = new global::PJ.Native.Proto.Container();
        }
        Container.MergeFrom(other.Container);
      }
      if (other.envelope_ != null) {
        if (envelope_ == null) {
          Envelope = new global::PJ.Native.Proto.Envelope();
        }
        Envelope.MergeFrom(other.Envelope);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (container_ == null) {
              Container = new global::PJ.Native.Proto.Container();
            }
            input.ReadMessage(Container);
            break;
          }
          case 26: {
            if (envelope_ == null) {
              Envelope = new global::PJ.Native.Proto.Envelope();
            }
            input.ReadMessage(Envelope);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (container_ == null) {
              Container = new global::PJ.Native.Proto.Container();
            }
            input.ReadMessage(Container);
            break;
          }
          case 26: {
            if (envelope_ == null) {
              Envelope = new global::PJ.Native.Proto.Envelope();
            }
            input.ReadMessage(Envelope);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Container : pb::IMessage<Container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Container> _parser = new pb::MessageParser<Container>(() => new Container());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PJ.Native.Proto.NativePubSubReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container(Container other) : this() {
      booleans_ = other.booleans_.Clone();
      integers_ = other.integers_.Clone();
      floats_ = other.floats_.Clone();
      strings_ = other.strings_.Clone();
      bytes_ = other.bytes_.Clone();
      containers_ = other.containers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container Clone() {
      return new Container(this);
    }

    /// <summary>Field number for the "booleans" field.</summary>
    public const int BooleansFieldNumber = 1;
    private static readonly pbc::MapField<string, bool>.Codec _map_booleans_codec
        = new pbc::MapField<string, bool>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBool(16, false), 10);
    private readonly pbc::MapField<string, bool> booleans_ = new pbc::MapField<string, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, bool> Booleans {
      get { return booleans_; }
    }

    /// <summary>Field number for the "integers" field.</summary>
    public const int IntegersFieldNumber = 2;
    private static readonly pbc::MapField<string, int>.Codec _map_integers_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 18);
    private readonly pbc::MapField<string, int> integers_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> Integers {
      get { return integers_; }
    }

    /// <summary>Field number for the "floats" field.</summary>
    public const int FloatsFieldNumber = 3;
    private static readonly pbc::MapField<string, float>.Codec _map_floats_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 26);
    private readonly pbc::MapField<string, float> floats_ = new pbc::MapField<string, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> Floats {
      get { return floats_; }
    }

    /// <summary>Field number for the "strings" field.</summary>
    public const int StringsFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_strings_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> strings_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Strings {
      get { return strings_; }
    }

    /// <summary>Field number for the "bytes" field.</summary>
    public const int BytesFieldNumber = 5;
    private static readonly pbc::MapField<string, pb::ByteString>.Codec _map_bytes_codec
        = new pbc::MapField<string, pb::ByteString>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 42);
    private readonly pbc::MapField<string, pb::ByteString> bytes_ = new pbc::MapField<string, pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, pb::ByteString> Bytes {
      get { return bytes_; }
    }

    /// <summary>Field number for the "containers" field.</summary>
    public const int ContainersFieldNumber = 6;
    private static readonly pbc::MapField<string, global::PJ.Native.Proto.Container>.Codec _map_containers_codec
        = new pbc::MapField<string, global::PJ.Native.Proto.Container>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::PJ.Native.Proto.Container.Parser), 50);
    private readonly pbc::MapField<string, global::PJ.Native.Proto.Container> containers_ = new pbc::MapField<string, global::PJ.Native.Proto.Container>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::PJ.Native.Proto.Container> Containers {
      get { return containers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Booleans.Equals(other.Booleans)) return false;
      if (!Integers.Equals(other.Integers)) return false;
      if (!Floats.Equals(other.Floats)) return false;
      if (!Strings.Equals(other.Strings)) return false;
      if (!Bytes.Equals(other.Bytes)) return false;
      if (!Containers.Equals(other.Containers)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Booleans.GetHashCode();
      hash ^= Integers.GetHashCode();
      hash ^= Floats.GetHashCode();
      hash ^= Strings.GetHashCode();
      hash ^= Bytes.GetHashCode();
      hash ^= Containers.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      booleans_.WriteTo(output, _map_booleans_codec);
      integers_.WriteTo(output, _map_integers_codec);
      floats_.WriteTo(output, _map_floats_codec);
      strings_.WriteTo(output, _map_strings_codec);
      bytes_.WriteTo(output, _map_bytes_codec);
      containers_.WriteTo(output, _map_containers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      booleans_.WriteTo(ref output, _map_booleans_codec);
      integers_.WriteTo(ref output, _map_integers_codec);
      floats_.WriteTo(ref output, _map_floats_codec);
      strings_.WriteTo(ref output, _map_strings_codec);
      bytes_.WriteTo(ref output, _map_bytes_codec);
      containers_.WriteTo(ref output, _map_containers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += booleans_.CalculateSize(_map_booleans_codec);
      size += integers_.CalculateSize(_map_integers_codec);
      size += floats_.CalculateSize(_map_floats_codec);
      size += strings_.CalculateSize(_map_strings_codec);
      size += bytes_.CalculateSize(_map_bytes_codec);
      size += containers_.CalculateSize(_map_containers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Container other) {
      if (other == null) {
        return;
      }
      booleans_.MergeFrom(other.booleans_);
      integers_.MergeFrom(other.integers_);
      floats_.MergeFrom(other.floats_);
      strings_.MergeFrom(other.strings_);
      bytes_.MergeFrom(other.bytes_);
      containers_.MergeFrom(other.containers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            booleans_.AddEntriesFrom(input, _map_booleans_codec);
            break;
          }
          case 18: {
            integers_.AddEntriesFrom(input, _map_integers_codec);
            break;
          }
          case 26: {
            floats_.AddEntriesFrom(input, _map_floats_codec);
            break;
          }
          case 34: {
            strings_.AddEntriesFrom(input, _map_strings_codec);
            break;
          }
          case 42: {
            bytes_.AddEntriesFrom(input, _map_bytes_codec);
            break;
          }
          case 50: {
            containers_.AddEntriesFrom(input, _map_containers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            booleans_.AddEntriesFrom(ref input, _map_booleans_codec);
            break;
          }
          case 18: {
            integers_.AddEntriesFrom(ref input, _map_integers_codec);
            break;
          }
          case 26: {
            floats_.AddEntriesFrom(ref input, _map_floats_codec);
            break;
          }
          case 34: {
            strings_.AddEntriesFrom(ref input, _map_strings_codec);
            break;
          }
          case 42: {
            bytes_.AddEntriesFrom(ref input, _map_bytes_codec);
            break;
          }
          case 50: {
            containers_.AddEntriesFrom(ref input, _map_containers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Envelope : pb::IMessage<Envelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Envelope> _parser = new pb::MessageParser<Envelope>(() => new Envelope());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PJ.Native.Proto.NativePubSubReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope(Envelope other) : this() {
      _hasBits0 = other._hasBits0;
      senderID_ = other.senderID_;
      receiverID_ = other.receiverID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope Clone() {
      return new Envelope(this);
    }

    /// <summary>Field number for the "senderID" field.</summary>
    public const int SenderIDFieldNumber = 1;
    private int senderID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SenderID {
      get { return senderID_; }
      set {
        senderID_ = value;
      }
    }

    /// <summary>Field number for the "receiverID" field.</summary>
    public const int ReceiverIDFieldNumber = 2;
    private readonly static int ReceiverIDDefaultValue = 0;

    private int receiverID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReceiverID {
      get { if ((_hasBits0 & 1) != 0) { return receiverID_; } else { return ReceiverIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        receiverID_ = value;
      }
    }
    /// <summary>Gets whether the "receiverID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasReceiverID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "receiverID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReceiverID() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SenderID != other.SenderID) return false;
      if (ReceiverID != other.ReceiverID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SenderID != 0) hash ^= SenderID.GetHashCode();
      if (HasReceiverID) hash ^= ReceiverID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SenderID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SenderID);
      }
      if (HasReceiverID) {
        output.WriteRawTag(16);
        output.WriteInt32(ReceiverID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SenderID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SenderID);
      }
      if (HasReceiverID) {
        output.WriteRawTag(16);
        output.WriteInt32(ReceiverID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SenderID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SenderID);
      }
      if (HasReceiverID) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceiverID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Envelope other) {
      if (other == null) {
        return;
      }
      if (other.SenderID != 0) {
        SenderID = other.SenderID;
      }
      if (other.HasReceiverID) {
        ReceiverID = other.ReceiverID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SenderID = input.ReadInt32();
            break;
          }
          case 16: {
            ReceiverID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SenderID = input.ReadInt32();
            break;
          }
          case 16: {
            ReceiverID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
